"""empty message

Revision ID: 17938e0bc7d1
Revises: a49b58b7e4a7
Create Date: 2019-11-02 19:38:45.183710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17938e0bc7d1'
down_revision = 'a49b58b7e4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_ibfk_1', 'activity', type_='foreignkey')
    op.drop_constraint('activity_ibfk_2', 'activity', type_='foreignkey')
    op.drop_column('activity', 'type_id')
    op.drop_column('activity', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('activity', sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('activity_ibfk_2', 'activity', 'like', ['type_id'], ['id'])
    op.create_foreign_key('activity_ibfk_1', 'activity', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
