"""empty message

Revision ID: 187c08e147b9
Revises: b36dcd907e1d
Create Date: 2019-09-23 22:16:50.722726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '187c08e147b9'
down_revision = 'b36dcd907e1d'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('like_x_user',
	sa.Column('id_user', sa.Integer(), nullable=False),
	sa.Column('id_like', sa.Integer(), nullable=False),
	sa.Column('flg_active', sa.Integer(), nullable=False),
	sa.Column('last_mod_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
	sa.ForeignKeyConstraint(['id_like'], ['like.id'], ),
	sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id_user', 'id_like')
	)
	op.drop_table('like_x__user')
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('like_x__user',
	sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
	sa.Column('id_like', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
	sa.Column('flg_active', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
	sa.Column('last_mod_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
	sa.ForeignKeyConstraint(['id_like'], ['like.id'], name='like_x__user_ibfk_1'),
	sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='like_x__user_ibfk_2'),
	sa.PrimaryKeyConstraint('id_user', 'id_like'),
	mysql_collate='utf8mb4_0900_ai_ci',
	mysql_default_charset='utf8mb4',
	mysql_engine='InnoDB'
	)
	op.drop_table('like_x_user')
	# ### end Alembic commands ###
