"""empty message

Revision ID: 19bcfb875602
Revises: 17938e0bc7d1
Create Date: 2019-11-02 23:14:34.581971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19bcfb875602'
down_revision = '17938e0bc7d1'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('organization', sa.Column('idCreator', sa.Integer(), nullable=True))
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('organization', 'idCreator')
	# ### end Alembic commands ###
