"""empty message

Revision ID: 1f78c5c530b4
Revises: 187c08e147b9
Create Date: 2019-10-21 01:32:40.348930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f78c5c530b4'
down_revision = '187c08e147b9'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('user', sa.Column('flg_special_user', sa.Integer(), nullable=False))
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('user', 'flg_special_user')
	# ### end Alembic commands ###
