"""empty message

Revision ID: 2a879ca5a40d
Revises: a22afa49325e
Create Date: 2019-11-17 20:35:02.347908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a879ca5a40d'
down_revision = 'a22afa49325e'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('chat',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('creation_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('last_message_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('kanban',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('name', sa.String(length=100), nullable=False),
	sa.Column('description', sa.String(length=255), nullable=False),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('like',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('name', sa.String(length=100), nullable=True),
	sa.Column('description', sa.String(length=1000), nullable=True),
	sa.Column('logodir', sa.String(length=500), nullable=True),
	sa.Column('create_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
	sa.Column('last_mod_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
	sa.PrimaryKeyConstraint('id'),
	sa.UniqueConstraint('logodir'),
	sa.UniqueConstraint('name')
	)
	op.create_table('notification_type',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('type', sa.String(length=100), nullable=False),
	sa.Column('description', sa.String(length=255), nullable=False),
	sa.Column('content', sa.String(length=255), nullable=False),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('organization',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('name', sa.String(length=100), nullable=False),
	sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('telephone_number_1', sa.String(length=20), nullable=True),
	sa.Column('telephone_number_2', sa.String(length=20), nullable=True),
	sa.Column('email_1', sa.String(length=50), nullable=True),
	sa.Column('email_2', sa.String(length=50), nullable=True),
	sa.Column('direction', sa.String(length=100), nullable=True),
	sa.Column('flg_active', sa.Integer(), nullable=False),
	sa.Column('image_direction', sa.String(length=255), nullable=True),
	sa.Column('id_creator', sa.Integer(), nullable=True),
	sa.Column('reference_1', sa.String(length=50), nullable=False),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('user',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('email', sa.String(length=100), nullable=True),
	sa.Column('username', sa.String(length=100), nullable=True),
	sa.Column('password', sa.String(length=100), nullable=True),
	sa.Column('name', sa.String(length=100), nullable=True),
	sa.Column('flg_special_user', sa.Integer(), nullable=False),
	sa.Column('telephone_number_1', sa.String(length=20), nullable=True),
	sa.Column('telephone_number_2', sa.String(length=20), nullable=True),
	sa.Column('email_1', sa.String(length=50), nullable=True),
	sa.Column('email_2', sa.String(length=50), nullable=True),
	sa.Column('direction', sa.String(length=100), nullable=True),
	sa.PrimaryKeyConstraint('id'),
	sa.UniqueConstraint('email'),
	sa.UniqueConstraint('username')
	)
	op.create_table('chat_x_user',
	sa.Column('user_id', sa.Integer(), nullable=False),
	sa.Column('chat_id', sa.Integer(), nullable=False),
	sa.Column('flg_visible', sa.Integer(), nullable=False),
	sa.Column('flg_eliminated', sa.Integer(), nullable=False),
	sa.Column('flg_archived', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('user_id', 'chat_id')
	)
	op.create_table('like_x_user',
	sa.Column('id_user', sa.Integer(), nullable=False),
	sa.Column('id_like', sa.Integer(), nullable=False),
	sa.Column('flg_active', sa.Integer(), nullable=False),
	sa.Column('last_mod_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
	sa.ForeignKeyConstraint(['id_like'], ['like.id'], ),
	sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id_user', 'id_like')
	)
	op.create_table('message',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('user_id', sa.Integer(), nullable=False),
	sa.Column('chat_id', sa.Integer(), nullable=False),
	sa.Column('send_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('content', sa.String(length=255), nullable=False),
	sa.Column('flg_visible_sender', sa.Integer(), nullable=False),
	sa.Column('flg_visible_receiver', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id', 'user_id', 'chat_id')
	)
	op.create_table('notification',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('user_id', sa.Integer(), nullable=False),
	sa.Column('notification_type_id', sa.Integer(), nullable=False),
	sa.Column('description', sa.String(length=255), nullable=False),
	sa.Column('flg_seen', sa.Integer(), nullable=False),
	sa.Column('notification_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('seen_date', sa.DateTime(), nullable=True),
	sa.ForeignKeyConstraint(['notification_type_id'], ['notification_type.id'], ),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('points',
	sa.Column('user_id', sa.Integer(), nullable=False),
	sa.Column('send_user_id', sa.Integer(), nullable=False),
	sa.Column('quantity', sa.Integer(), nullable=False),
	sa.Column('content', sa.String(length=255), nullable=False),
	sa.Column('send_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.ForeignKeyConstraint(['send_user_id'], ['user.id'], ),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('user_id', 'send_user_id')
	)
	op.create_table('project',
	sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
	sa.Column('organization_id', sa.Integer(), nullable=False),
	sa.Column('name', sa.String(length=100), nullable=False),
	sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('flg_active', sa.Integer(), nullable=False),
	sa.Column('image_direction', sa.String(length=255), nullable=True),
	sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
	sa.PrimaryKeyConstraint('id', 'organization_id')
	)
	op.create_table('report',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('user_id', sa.Integer(), nullable=False),
	sa.Column('send_user_id', sa.Integer(), nullable=False),
	sa.Column('message', sa.String(length=255), nullable=False),
	sa.Column('send_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.ForeignKeyConstraint(['send_user_id'], ['user.id'], ),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id', 'user_id', 'send_user_id')
	)
	op.create_table('user_x_organization',
	sa.Column('organization_id', sa.Integer(), nullable=False),
	sa.Column('user_id', sa.Integer(), nullable=False),
	sa.Column('flg_active', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('organization_id', 'user_id')
	)
	op.create_table('activity',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('project_id', sa.Integer(), nullable=False),
	sa.Column('title', sa.String(length=100), nullable=True),
	sa.Column('description', sa.String(length=1000), nullable=True),
	sa.Column('latitude', sa.Float(), nullable=True),
	sa.Column('longitude', sa.Float(), nullable=True),
	sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
	sa.PrimaryKeyConstraint('id', 'project_id'),
	sa.UniqueConstraint('title')
	)
	op.create_table('kanban_x_activity',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('project_id', sa.Integer(), nullable=False),
	sa.Column('kanban_type_id', sa.Integer(), nullable=False),
	sa.Column('creation_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('name', sa.String(length=100), nullable=False),
	sa.Column('description', sa.String(length=255), nullable=True),
	sa.Column('modification_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('limit_date', sa.DateTime(), nullable=True),
	sa.ForeignKeyConstraint(['kanban_type_id'], ['kanban.id'], ),
	sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('news',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('project_id', sa.Integer(), nullable=False),
	sa.Column('title', sa.String(length=100), nullable=True),
	sa.Column('description', sa.String(length=1000), nullable=True),
	sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
	sa.PrimaryKeyConstraint('id', 'project_id')
	)
	op.create_table('task',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('project_id', sa.Integer(), nullable=False),
	sa.Column('creation_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('name', sa.String(length=100), nullable=False),
	sa.Column('description', sa.String(length=255), nullable=True),
	sa.Column('modification_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('init_date', sa.DateTime(), nullable=True),
	sa.Column('finish_date', sa.DateTime(), nullable=True),
	sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
	sa.PrimaryKeyConstraint('id', 'project_id')
	)
	op.create_table('coments',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('news_id', sa.Integer(), nullable=False),
	sa.Column('user_id', sa.Integer(), nullable=False),
	sa.Column('publication_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('type', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id', 'news_id', 'user_id')
	)
	op.create_table('comments',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('news_id', sa.Integer(), nullable=False),
	sa.Column('user_id', sa.Integer(), nullable=False),
	sa.Column('publication_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('description', sa.String(length=255), nullable=False),
	sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id', 'news_id', 'user_id')
	)
	op.create_table('enrollment',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('user_id', sa.Integer(), nullable=True),
	sa.Column('activity_id', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('schedule',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('project_id', sa.Integer(), nullable=False),
	sa.Column('description', sa.String(length=1000), nullable=True),
	sa.Column('start_date', sa.DateTime(), nullable=True),
	sa.Column('end_date', sa.DateTime(), nullable=True),
	sa.Column('activity_id', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
	sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
	sa.PrimaryKeyConstraint('id', 'project_id')
	)
	op.create_table('staff_x_activity',
	sa.Column('activity_id', sa.Integer(), nullable=False),
	sa.Column('user_id', sa.Integer(), nullable=False),
	sa.Column('flg_active', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('activity_id', 'user_id')
	)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('staff_x_activity')
	op.drop_table('schedule')
	op.drop_table('enrollment')
	op.drop_table('comments')
	op.drop_table('coments')
	op.drop_table('task')
	op.drop_table('news')
	op.drop_table('kanban_x_activity')
	op.drop_table('activity')
	op.drop_table('user_x_organization')
	op.drop_table('report')
	op.drop_table('project')
	op.drop_table('points')
	op.drop_table('notification')
	op.drop_table('message')
	op.drop_table('like_x_user')
	op.drop_table('chat_x_user')
	op.drop_table('user')
	op.drop_table('organization')
	op.drop_table('notification_type')
	op.drop_table('like')
	op.drop_table('kanban')
	op.drop_table('chat')
	# ### end Alembic commands ###
