"""empty message

Revision ID: 3daea9358983
Revises: 0a7d1f624961
Create Date: 2019-08-06 20:19:42.188089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3daea9358983'
down_revision = '0a7d1f624961'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('news',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('title', sa.String(length=100), nullable=True),
	sa.Column('description', sa.String(length=1000), nullable=True),
	sa.Column('activity_id', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('news')
	# ### end Alembic commands ###
