"""empty message

Revision ID: 4efdefeb23c4
Revises: 43fa380491d9
Create Date: 2019-09-01 23:12:59.753538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4efdefeb23c4'
down_revision = '43fa380491d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('user', sa.Column('facebook', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('linkedin', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('membership', sa.String(), nullable=True))
    op.add_column('user', sa.Column('points', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['linkedin'])
    op.create_unique_constraint(None, 'user', ['facebook'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'points')
    op.drop_column('user', 'membership')
    op.drop_column('user', 'linkedin')
    op.drop_column('user', 'facebook')
    op.drop_column('user', 'description')
    # ### end Alembic commands ###
