"""empty message

Revision ID: 9b32067f601a
Revises: 1a6d1152102e
Create Date: 2019-09-15 21:07:25.486058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b32067f601a'
down_revision = '1a6d1152102e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activity', 'like', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_column('activity', 'type_id')
    # ### end Alembic commands ###
