"""empty message

Revision ID: a49b58b7e4a7
Revises: df2872ec1f1e
Create Date: 2019-10-28 00:53:33.386629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49b58b7e4a7'
down_revision = 'df2872ec1f1e'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('activity', sa.Column('project_id', sa.Integer(), nullable=False))
	op.create_foreign_key(None, 'activity', 'project', ['project_id'], ['id'])
	op.add_column('kanban_x_activity', sa.Column('project_id', sa.Integer(), nullable=False))
	op.create_foreign_key(None, 'kanban_x_activity', 'project', ['project_id'], ['id'])
	op.add_column('news', sa.Column('project_id', sa.Integer(), nullable=False))
	op.create_foreign_key(None, 'news', 'project', ['project_id'], ['id'])
	op.add_column('schedule', sa.Column('project_id', sa.Integer(), nullable=False))
	op.create_foreign_key(None, 'schedule', 'project', ['project_id'], ['id'])
	op.add_column('task', sa.Column('project_id', sa.Integer(), nullable=False))
	op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'])
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint(None, 'task', type_='foreignkey')
	op.drop_column('task', 'project_id')
	op.drop_constraint(None, 'schedule', type_='foreignkey')
	op.drop_column('schedule', 'project_id')
	op.drop_constraint(None, 'news', type_='foreignkey')
	op.drop_column('news', 'project_id')
	op.drop_constraint(None, 'kanban_x_activity', type_='foreignkey')
	op.drop_column('kanban_x_activity', 'project_id')
	op.drop_constraint(None, 'activity', type_='foreignkey')
	op.drop_column('activity', 'project_id')
	# ### end Alembic commands ###
