"""empty message

Revision ID: a5f2ebecb01c
Revises: 1f78c5c530b4
Create Date: 2019-10-21 01:50:36.739156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f2ebecb01c'
down_revision = '1f78c5c530b4'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('chat',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('creation_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('last_message_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.PrimaryKeyConstraint('id')
	)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('chat')
	# ### end Alembic commands ###
