"""empty message

Revision ID: ae8f349a0dad
Revises: b0dfdd221887
Create Date: 2019-09-15 15:17:57.278237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8f349a0dad'
down_revision = 'b0dfdd221887'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('user',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('email', sa.String(length=100), nullable=True),
	sa.Column('username', sa.String(length=100), nullable=True),
	sa.Column('password', sa.String(length=100), nullable=True),
	sa.Column('name', sa.String(length=100), nullable=True),
	sa.PrimaryKeyConstraint('id'),
	sa.UniqueConstraint('email'),
	sa.UniqueConstraint('username')
	)
	op.create_table('activity',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('title', sa.String(length=100), nullable=True),
	sa.Column('description', sa.String(length=1000), nullable=True),
	sa.Column('latitude', sa.Float(), nullable=True),
	sa.Column('longitude', sa.Float(), nullable=True),
	sa.Column('user_id', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id'),
	sa.UniqueConstraint('title')
	)
	op.create_table('enrollment',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('user_id', sa.Integer(), nullable=True),
	sa.Column('activity_id', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('news',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('title', sa.String(length=100), nullable=True),
	sa.Column('description', sa.String(length=1000), nullable=True),
	sa.Column('activity_id', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('schedule',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('description', sa.String(length=1000), nullable=True),
	sa.Column('start_date', sa.DateTime(), nullable=True),
	sa.Column('end_date', sa.DateTime(), nullable=True),
	sa.Column('activity_id', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('schedule')
	op.drop_table('news')
	op.drop_table('enrollment')
	op.drop_table('activity')
	op.drop_table('user')
	# ### end Alembic commands ###
