"""empty message

Revision ID: b0dfdd221887
Revises: bbbf30b545cf
Create Date: 2019-08-06 21:12:32.710012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0dfdd221887'
down_revision = 'bbbf30b545cf'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('activity', sa.Column('user_id', sa.Integer(), nullable=True))
	op.create_foreign_key(None, 'activity', 'user', ['user_id'], ['id'])
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint(None, 'activity', type_='foreignkey')
	op.drop_column('activity', 'user_id')
	# ### end Alembic commands ###
