"""empty message

Revision ID: df2872ec1f1e
Revises: ad40775af877
Create Date: 2019-10-28 00:49:33.989893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df2872ec1f1e'
down_revision = 'ad40775af877'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('organization',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('name', sa.String(length=100), nullable=False),
	sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('telephone_number_1', sa.String(length=20), nullable=True),
	sa.Column('telephone_number_2', sa.String(length=20), nullable=True),
	sa.Column('email_1', sa.String(length=50), nullable=True),
	sa.Column('email_2', sa.String(length=50), nullable=True),
	sa.Column('direction', sa.String(length=100), nullable=True),
	sa.Column('flg_active', sa.Integer(), nullable=False),
	sa.Column('image_direction', sa.String(length=255), nullable=True),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('task',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('creation_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('name', sa.String(length=100), nullable=False),
	sa.Column('description', sa.String(length=255), nullable=True),
	sa.Column('modification_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('init_date', sa.DateTime(), nullable=True),
	sa.Column('finish_date', sa.DateTime(), nullable=True),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('chat_x_user',
	sa.Column('user_id', sa.Integer(), nullable=False),
	sa.Column('chat_id', sa.Integer(), nullable=False),
	sa.Column('flg_visible', sa.Integer(), nullable=False),
	sa.Column('flg_eliminated', sa.Integer(), nullable=False),
	sa.Column('flg_archived', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('user_id', 'chat_id')
	)
	op.create_table('project',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('organization_id', sa.Integer(), nullable=False),
	sa.Column('name', sa.String(length=100), nullable=False),
	sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
	sa.Column('flg_active', sa.Integer(), nullable=False),
	sa.Column('image_direction', sa.String(length=255), nullable=True),
	sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
	sa.PrimaryKeyConstraint('id', 'organization_id')
	)
	op.create_table('user_x_organization',
	sa.Column('organization_id', sa.Integer(), nullable=False),
	sa.Column('user_id', sa.Integer(), nullable=False),
	sa.Column('flg_active', sa.Integer(), nullable=False),
	sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
	sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
	sa.PrimaryKeyConstraint('organization_id', 'user_id')
	)
	op.drop_table('contact')
	op.drop_constraint('kanban_x_activity_ibfk_1', 'kanban_x_activity', type_='foreignkey')
	op.drop_column('kanban_x_activity', 'activity_id')
	op.drop_constraint('news_ibfk_1', 'news', type_='foreignkey')
	op.drop_column('news', 'activity_id')
	op.add_column('user', sa.Column('direction', sa.String(length=100), nullable=True))
	op.add_column('user', sa.Column('email_1', sa.String(length=50), nullable=True))
	op.add_column('user', sa.Column('email_2', sa.String(length=50), nullable=True))
	op.add_column('user', sa.Column('telephone_number_1', sa.String(length=20), nullable=True))
	op.add_column('user', sa.Column('telephone_number_2', sa.String(length=20), nullable=True))
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('user', 'telephone_number_2')
	op.drop_column('user', 'telephone_number_1')
	op.drop_column('user', 'email_2')
	op.drop_column('user', 'email_1')
	op.drop_column('user', 'direction')
	op.add_column('news', sa.Column('activity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
	op.create_foreign_key('news_ibfk_1', 'news', 'activity', ['activity_id'], ['id'])
	op.add_column('kanban_x_activity', sa.Column('activity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
	op.create_foreign_key('kanban_x_activity_ibfk_1', 'kanban_x_activity', 'activity', ['activity_id'], ['id'])
	op.create_table('contact',
	sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
	sa.Column('activity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
	sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
	sa.Column('telephone_number_1', mysql.VARCHAR(length=20), nullable=True),
	sa.Column('telephone_number_2', mysql.VARCHAR(length=20), nullable=True),
	sa.Column('email_1', mysql.VARCHAR(length=50), nullable=True),
	sa.Column('email_2', mysql.VARCHAR(length=50), nullable=True),
	sa.Column('direction', mysql.VARCHAR(length=100), nullable=True),
	sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='contact_ibfk_1'),
	sa.PrimaryKeyConstraint('id'),
	mysql_collate='utf8mb4_0900_ai_ci',
	mysql_default_charset='utf8mb4',
	mysql_engine='InnoDB'
	)
	op.drop_table('user_x_organization')
	op.drop_table('project')
	op.drop_table('chat_x_user')
	op.drop_table('task')
	op.drop_table('organization')
	# ### end Alembic commands ###
